[package]
name = "auth_client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Authentication Client – shared models, DTOs and HTTP client for the Auth Authentication Server"

[features]
default = []
# _server: additional types/impls used by auth_server
#   - actix_web::ResponseError for AuthError
_server = ["dep:actix-web"]

[dependencies]
actix-web = { workspace = true, optional = true }
base64 = { workspace = true }
cookie_store = { workspace = true }
cosmian_logger = { workspace = true }
reqwest = { workspace = true, features = [
    "json",
    "native-tls",
    "socks",
    "http2",
    "cookies",
] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[lib]
path = "src/lib.rs"

[dev-dependencies]
