//! 2FA/TOTP (Time-based One-Time Password) utilities
//!
//! This module provides functionality for implementing two-factor authentication
//! using TOTP codes generated by authenticator apps.
//!
//! # Features
//! - Generate random TOTP secrets
//! - Create `otpauth://` URLs for QR code generation
//! - Validate TOTP tokens with a time window
//! - Enable/disable 2FA for users

use crate::{AuthError, AuthResult};
pub use auth_client::TotpRealmParams;
use totp_rs::{Algorithm, Secret, TOTP};

/// Internal TOTP configuration parameters
///
/// These follow common industry standards (Google Authenticator, Authy, etc.)
#[derive(Clone)]
pub struct TotpParams {
    /// TOTP algorithm (default: SHA1)
    pub algorithm: Algorithm,
    /// Code length in digits (default: 6)
    pub digits: usize,
    /// Number of allowed steps of skew (default: 1)
    pub skew: u8,
    /// Time step in seconds for token rotation (default: 30)
    pub step: u64,
}

impl Default for TotpParams {
    fn default() -> Self {
        Self {
            algorithm: Algorithm::SHA1,
            digits: 6,
            skew: 1,
            step: 30,
        }
    }
}

/// Convert realm-level TOTP configuration into the internal `TotpParams`.
pub fn realm_params_to_totp_params(p: &TotpRealmParams) -> AuthResult<TotpParams> {
    let algorithm = match p.algorithm.to_ascii_uppercase().as_str() {
        "SHA1" => Algorithm::SHA1,
        "SHA256" => Algorithm::SHA256,
        "SHA512" => Algorithm::SHA512,
        other => {
            return Err(AuthError::Totp(format!(
                "Unknown TOTP algorithm '{other}'; supported values: SHA1, SHA256, SHA512"
            )));
        }
    };
    Ok(TotpParams {
        algorithm,
        digits: 6,
        skew: 1,
        step: p.step,
    })
}

/// A configured TOTP instance with its parameters
#[derive(Clone)]
pub struct Totps {
    totp: TOTP,
}

impl Totps {
    /// Creates a new `Totps` instance with a randomly generated secret and default parameters.
    pub fn new() -> AuthResult<Self> {
        Self::with_params_and_account(TotpParams::default(), None, String::new())
    }

    /// Creates a new `Totps` from a known Base32 secret, issuer, and account name,
    /// using the provided `TotpParams` (or the defaults if `None`).
    pub fn from_secret(
        secret_base32: &str,
        issuer: Option<String>,
        account_name: String,
        params: Option<TotpParams>,
    ) -> AuthResult<Self> {
        let params = params.unwrap_or_default();
        // Why is the value stored in base and not in bytes directly?
        let secret_bytes = Secret::Encoded(secret_base32.to_string())
            .to_bytes()
            .map_err(|e| AuthError::Totp(format!("Invalid Base32 secret: {e}")))?;

        let totp = TOTP::new(
            params.algorithm,
            params.digits,
            params.skew,
            params.step,
            secret_bytes,
            issuer,
            account_name,
        )
        .map_err(|e| AuthError::Totp(format!("Failed to create TOTP: {e}")))?;

        Ok(Self { totp })
    }

    /// Creates a new `Totps` instance with custom parameters.
    fn with_params_and_account(
        params: TotpParams,
        issuer: Option<String>,
        account_name: String,
    ) -> AuthResult<Self> {
        let secret = Secret::generate_secret();
        let secret_bytes = secret
            .to_bytes()
            .map_err(|e| AuthError::Totp(format!("Failed to generate secret: {e}")))?;

        let totp = TOTP::new(
            params.algorithm,
            params.digits,
            params.skew,
            params.step,
            secret_bytes,
            issuer,
            account_name,
        )
        .map_err(|e| AuthError::Totp(format!("Failed to create TOTP: {e}")))?;

        Ok(Self { totp })
    }

    /// Returns the Base32-encoded secret.
    pub fn generate_secret(&self) -> String {
        self.totp.get_secret_base32()
    }

    /// Returns the `otpauth://` URL (useful for QR code generation).
    pub fn get_otpauth_url(&self) -> String {
        self.totp.get_url()
    }

    /// Validates a TOTP token against the current time.
    ///
    /// Returns `true` if the token is valid (within the configured skew window).
    pub fn validate_token(&self, token: &str) -> Result<bool, AuthError> {
        self.totp
            .check_current(token)
            .map_err(|e| AuthError::Totp(format!("System time error: {e}")))
    }

    /// Gets the current TOTP code for this instance.
    pub fn generate_current_token(&self) -> Result<String, AuthError> {
        self.totp
            .generate_current()
            .map_err(|e| AuthError::Totp(format!("System time error: {e}")))
    }

    /// Creates a new Totps instance with a randomly generated secret,
    /// configured for a given issuer, account name, and optional realm parameters.
    /// Returns the instance and the Base32-encoded secret.
    pub fn generate_secret_and_totps(
        issuer: &str,
        account_name: &str,
        params: Option<TotpParams>,
    ) -> AuthResult<(Self, String)> {
        let totps = Self::with_params_and_account(
            params.unwrap_or_default(),
            Some(issuer.to_string()),
            account_name.to_string(),
        )?;
        let secret_base32 = totps.generate_secret();
        Ok((totps, secret_base32))
    }
}

/// Creates a new TOTP secret.
///
/// # Arguments
/// * `issuer` - The application name for the QR code URL
/// * `account_name` - The user's account identifier
/// * `params` - Optional realm-level TOTP parameters; defaults to SHA1 / 30-second step if `None`
///
/// Returns the configured `Totps` instance and the Base32-encoded secret.
pub fn create_totp_secret(
    issuer: &str,
    account_name: &str,
    params: Option<TotpParams>,
) -> AuthResult<(Totps, String)> {
    Totps::generate_secret_and_totps(issuer, account_name, params)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_secret() {
        let totps = Totps::new().expect("Failed to create Totps");
        let secret = totps.generate_secret();
        assert!(!secret.is_empty());
    }

    #[test]
    fn test_otpauth_url() {
        let (totps, _secret) = Totps::generate_secret_and_totps("Auth", "user@example.com", None)
            .expect("Failed to generate TOTP");
        let url = totps.get_otpauth_url();
        assert!(url.starts_with("otpauth://totp/"));
        assert!(url.contains("Auth"));
        assert!(url.contains("user%40example.com") || url.contains("user@example.com"));
    }

    #[test]
    fn test_from_known_secret() {
        let (totps, secret) = Totps::generate_secret_and_totps("Auth", "test@example.com", None)
            .expect("Failed to generate TOTP");

        // Re-create from the known secret
        let totps2 = Totps::from_secret(
            &secret,
            Some("Auth".to_string()),
            "test@example.com".to_string(),
            None,
        )
        .expect("Failed to recreate from secret");

        // Both should generate the same token for the same instant
        let token1 = totps.generate_current_token().expect("token1");
        let token2 = totps2.generate_current_token().expect("token2");
        assert_eq!(token1, token2);
    }

    #[test]
    fn test_validate_own_token() {
        let (totps, _) = Totps::generate_secret_and_totps("Auth", "test@example.com", None)
            .expect("Failed to generate TOTP");

        let token = totps
            .generate_current_token()
            .expect("Failed to generate token");
        let valid = totps.validate_token(&token).expect("Failed to validate");
        assert!(valid, "Token should be valid right after generation");
    }

    #[test]
    fn test_invalid_token_rejected() {
        let (totps, _) = Totps::generate_secret_and_totps("Auth", "test@example.com", None)
            .expect("Failed to generate TOTP");

        // Use a clearly wrong token: "999999" will be invalid in the vast majority of cases
        // We validate the method executes without panic; the bool result depends on timing
        let result = totps.validate_token("999999");
        assert!(result.is_ok(), "validate_token should not error");
    }

    #[test]
    fn test_malformed_token_rejected() {
        let (totps, _) = Totps::generate_secret_and_totps("Auth", "test@example.com", None)
            .expect("Failed to generate TOTP");

        // Non-numeric token should be rejected
        let valid = totps.validate_token("abcdef").expect("should not error");
        assert!(!valid, "Non-numeric token must be rejected");
    }

    #[test]
    fn test_wrong_length_token_rejected() {
        let (totps, _) = Totps::generate_secret_and_totps("Auth", "test@example.com", None)
            .expect("Failed to generate TOTP");

        // Token with wrong number of digits
        let valid = totps.validate_token("12345").expect("should not error");
        assert!(!valid, "5-digit token must be rejected for 6-digit TOTP");

        let valid = totps.validate_token("1234567").expect("should not error");
        assert!(!valid, "7-digit token must be rejected for 6-digit TOTP");
    }

    #[test]
    fn test_empty_token_rejected() {
        let (totps, _) = Totps::generate_secret_and_totps("Auth", "test@example.com", None)
            .expect("Failed to generate TOTP");

        let valid = totps.validate_token("").expect("should not error");
        assert!(!valid, "Empty token must be rejected");
    }

    #[test]
    fn test_from_invalid_base32_secret_fails() {
        let result = Totps::from_secret(
            "!!!invalid!!!",
            Some("Auth".to_string()),
            "user".to_string(),
            None,
        );
        assert!(
            result.is_err(),
            "Invalid Base32 secret must produce an error"
        );
    }

    #[test]
    fn test_two_independent_secrets_differ() {
        let (_, secret1) = Totps::generate_secret_and_totps("Auth", "user1@example.com", None)
            .expect("Failed to generate TOTP 1");
        let (_, secret2) = Totps::generate_secret_and_totps("Auth", "user2@example.com", None)
            .expect("Failed to generate TOTP 2");

        assert_ne!(secret1, secret2, "Two generated secrets must differ");
    }

    #[test]
    fn test_different_accounts_same_secret_produce_same_token() {
        // TOTP token depends only on secret + time, not account name
        let (_, secret) = Totps::generate_secret_and_totps("Auth", "alice@example.com", None)
            .expect("Failed to generate TOTP");

        let t1 = Totps::from_secret(
            &secret,
            Some("Auth".to_string()),
            "alice@example.com".to_string(),
            None,
        )
        .expect("from_secret 1");
        let t2 = Totps::from_secret(
            &secret,
            Some("Auth".to_string()),
            "bob@example.com".to_string(),
            None,
        )
        .expect("from_secret 2");

        let tok1 = t1.generate_current_token().expect("token 1");
        let tok2 = t2.generate_current_token().expect("token 2");
        assert_eq!(
            tok1, tok2,
            "Same secret at same time must produce same token regardless of account name"
        );
    }

    #[test]
    fn test_create_totp_secret_convenience() {
        let (totps, secret) = create_totp_secret("TestApp", "admin@test.com", None)
            .expect("create_totp_secret failed");
        assert!(!secret.is_empty());
        let url = totps.get_otpauth_url();
        assert!(url.contains("TestApp"));
        assert!(url.contains("admin"));
    }

    #[test]
    fn test_default_params() {
        let params = TotpParams::default();
        assert_eq!(params.digits, 6);
        assert_eq!(params.skew, 1);
        assert_eq!(params.step, 30);
    }

    #[test]
    fn test_totp_realm_params_sha256() {
        let realm_params = TotpRealmParams {
            algorithm: "SHA256".to_string(),
            step: 60,
        };
        let totp_params = realm_params_to_totp_params(&realm_params).expect("SHA256 must be valid");
        assert_eq!(totp_params.step, 60);

        let (totps, secret) =
            Totps::generate_secret_and_totps("Auth", "alice", Some(totp_params.clone()))
                .expect("generate with SHA256 failed");
        let totps2 = Totps::from_secret(
            &secret,
            Some("Auth".to_string()),
            "alice".to_string(),
            Some(totp_params),
        )
        .expect("from_secret SHA256 failed");

        assert_eq!(
            totps.generate_current_token().expect("token 1"),
            totps2.generate_current_token().expect("token 2"),
            "Same secret and algorithm must produce the same token"
        );
    }

    #[test]
    fn test_totp_realm_params_invalid_algorithm() {
        let realm_params = TotpRealmParams {
            algorithm: "MD5".to_string(),
            step: 30,
        };
        assert!(
            realm_params_to_totp_params(&realm_params).is_err(),
            "Unsupported algorithm must return an error"
        );
    }
}
