use serde::{Deserialize, Serialize};

/// Default grant types for a newly registered OAuth client.
fn default_grant_types() -> Vec<String> {
    vec![
        "authorization_code".to_string(),
        "refresh_token".to_string(),
    ]
}

/// Default response types (only `code` — no implicit/hybrid).
fn default_response_types() -> Vec<String> {
    vec!["code".to_string()]
}

/// Default token-endpoint client authentication method.
fn default_token_endpoint_auth_method() -> String {
    "client_secret_basic".to_string()
}

/// Request body to create or update an OAuth 2.0 / OIDC client.
///
/// The `client_id` and `client_secret` are generated by the server on creation
/// (for confidential clients); the secret is returned **once** in the creation
/// response and never again.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OAuthClientRequest {
    /// Human-readable client name.
    pub client_name: String,
    /// Allowed redirect URIs (exact match at the authorization endpoint).
    pub redirect_uris: Vec<String>,
    /// Allowed grant types.
    #[serde(default = "default_grant_types")]
    pub grant_types: Vec<String>,
    /// Allowed response types (only `code` is accepted).
    #[serde(default = "default_response_types")]
    pub response_types: Vec<String>,
    /// Scopes this client may request.
    #[serde(default)]
    pub scopes: Vec<String>,
    /// Token-endpoint client authentication method:
    /// `client_secret_basic`, `client_secret_post`, or `none` (public/PKCE-only).
    #[serde(default = "default_token_endpoint_auth_method")]
    pub token_endpoint_auth_method: String,
}

/// Response describing a registered OAuth client.
///
/// `client_secret` is populated **only** in the response to a client-creation
/// request; subsequent reads omit it.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OAuthClientResponse {
    pub client_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
    pub client_name: String,
    pub redirect_uris: Vec<String>,
    pub grant_types: Vec<String>,
    pub response_types: Vec<String>,
    pub scopes: Vec<String>,
    pub token_endpoint_auth_method: String,
    pub realm: String,
    pub created_at: i64,
}
