use crate::{
    AuthError, AuthResult,
    server::{parameters::ServerParams, start_auth_server},
    tests::{TestsContext, get_default_server_params},
};
use actix_web::dev::ServerHandle;
use cosmian_logger::{error, info};
use std::{
    sync::{Arc, mpsc},
    thread,
};

/// Starts the test server in a separate thread and returns a `TestsContext` containing
/// the server handle and thread handle.
pub async fn start_test_server(server_params: ServerParams) -> AuthResult<TestsContext> {
    let (tx, rx) = mpsc::channel::<ServerHandle>();

    let params = Arc::new(server_params.clone());
    let thread_handle = thread::spawn(move || {
        // allow others `spawn` to happen within the Authentication Server in the future
        let runtime = tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .map_err(|e| {
                error!("Error building tokio runtime: {e:?}");
                AuthError::Unexpected(e.to_string())
            })?;

        runtime
            .block_on(start_auth_server(params, Some(tx)))
            .map_err(|e| {
                error!("Error starting the Authentication server: {e:?}");
                AuthError::Unexpected(e.to_string())
            })
    });

    info!("Waiting 10 seconds to receive the test server handle...");
    let server_handle = rx
        .recv_timeout(std::time::Duration::from_secs(10))
        .map_err(|e| AuthError::Unexpected(format!("Error getting test server handle: {e}")))?;

    Ok(TestsContext {
        server_params,
        server_handle,
        thread_handle,
    })
}

/// Starts a default test server with predefined parameters.
/// Returns a `TestsContext` containing the server handle and thread handle.
///
/// When called in parallel by multiple tests, each server will use a unique port
/// number generated by incrementing an atomic counter, avoiding port conflicts.
pub async fn start_default_test_server() -> AuthResult<TestsContext> {
    start_test_server(get_default_server_params()?).await
}

mod tests {

    use cosmian_logger::info;
    use tokio::time::sleep;

    use crate::{AuthError, tests::test_server::start_default_test_server};

    #[tokio::test]
    async fn test_start_server() -> Result<(), AuthError> {
        // init_test_logging(Some("info"));
        info!("Starting test server...");
        let ctx = start_default_test_server().await?;
        info!("Test server started successfully. Sleeping for 3 seconds...");
        sleep(std::time::Duration::from_secs(3)).await;
        info!("Stopping test server...");
        ctx.stop_server().await?;
        info!("Test server stopped.");
        Ok(())
    }
}
