---
name: CI checks

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  cla-assistant:
    if: |
      (github.event.pull_request.head.repo.full_name != github.repository)
      && ((github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA')
          || github.event_name == 'pull_request_target')
    uses: ./.github/workflows/cla.yml
    secrets: inherit

  cargo-deny:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-audit.yml@develop
    name: Security Audit
    with:
      toolchain: ${{ inputs.toolchain }}

  cargo-machete:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-machete.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}

  cargo-clippy:
    name: Cargo test - ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm, macos-15]

    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: rustfmt, clippy

      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Run unit tests
        run: cargo fmt --all -- --check --color always

      - name: Static analysis
        run: cargo clippy --workspace --all-targets -- -D warnings

      # - name: Static analysis all features
      #   run: cargo clippy --workspace --all-targets --no-default-features --features database,rustls -- -D warnings

  cargo-test:
    name: Cargo test - ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm, macos-15]

    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: rustfmt, clippy

      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Run unit tests
        run: |
          cargo test --workspace --lib -- --nocapture
