---
name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - fix/**
      - chore/**
      - ci/**
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/main_base.yml
    secrets: inherit
    with:
      toolchain: stable
